spring.application.name=gamefinder

spring.datasource.url=jdbc:h2:mem:gamefinder
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
